name: qczj

on:
    workflow_dispatch:
    schedule:
        - cron: "*/30 * * * *"
    watch:
        types: [started]
    repository_dispatch:
        types: jd_crazy_joy_coin

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
            - name: 拉取代码
              uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: "12.x"
            - name: 安装依赖包
              run: |
                  npm install
            - name: "运行【qczj】"
              run: |
                  node Task/qczjspeed.js
              env:
                QCZJ_GetUserInfoHEADER: ${{ secrets.QCZJ_GetUserInfoHEADER }}
                QCZJ_taskBODY: ${{ secrets.QCZJ_taskBODY }}		
                QCZJ_activityBODY: ${{ secrets.QCZJ_activityBODY }}	
                QCZJ_addCoinBODY: ${{ secrets.QCZJ_addCoinBODY }}
                QCZJ_addCoin2BODY: ${{ secrets.QCZJ_addCoin2BODY }}
                QCZJ_CASH: ${{ secrets.QCZJ_CASH }}
                QCZJ_CASHTIME: ${{ secrets.QCZJ_CASHTIME }}
                PUSH_KEY: ${{ secrets.PUSH_KEY }}
                BARK_PUSH: ${{ secrets.BARK_PUSH }}
                TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
                TG_USER_ID: ${{ secrets.TG_USER_ID }}
                BARK_SOUND: ${{ secrets.BARK_SOUND }}
                DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
                DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
